add python script for ubuntu
amperka/ESP8266-uploader-script pull request #1
Opened 2020-08-17 14:43 UTC by S-VIN

Please write your comments and remarks. I will add comments in code after I correct them.
Python script only for ubuntu, because I download esptool using apt.

2020-08-17 15:46 UTC, AlexErAmp requested changes

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +        if((re.search("ttyUSB*", ports[i]) != None) or (re.search("ttyACM*", ports[i]) != None)):
According to pep8, the string should not exceed 79 characters. Format your code with python black with `--line-length= 79` option.

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +        raise Exeption(output.returncode)
```suggestion
        raise Exception(output.returncode)
```

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +    if(output.returncode != 0):
I think best practice doing like this:
```suggestion
try:
    subprocess.run(["sudo", "apt", "install", "esptool"], check=True)
except subprocess.CalledProcessError as err:
   raise err

```

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +        except:
Don't use bare except. What if I want to exit at this location with ctrl-c?

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +                break;
`;` - not needed

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +            if (num >= 0 and num < maxInput):
No parentheses needed.

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +    for i in range(len(ports) - 1):
More pythonic:
```suggestion
    for port in ports:
```

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +        if((re.search("ttyUSB*", ports[i]) != None) or (re.search("ttyACM*", ports[i]) != None)):
1) No parentheses needed.
2) Comparison to None should be 'if cond is not None:'

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +    for i in range(len(ports)):
```suggestion
    for port in ports:
```

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +            output.append(ports[i]);
`;` - not needed

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +    print(e);
`;` - not needed

2020-08-17 15:46 UTC, AlexErAmp commented on flash.py
> +    for i in range(len(firmwares)):
```suggestion
    for firmware in firmwares:
```

2020-08-17 16:07 UTC, nkrkv reviewed
Please run source through [Black](https://pypi.org/project/black/) and keep PEP 8 naming scheme

2020-08-18 16:08 UTC, AlexErAmp requested changes

2020-08-18 16:08 UTC, AlexErAmp commented on flash.py
> +    subprocess.run(
If `check` is `true`, and the process exits with a non-zero exit code, a `CalledProcessError` exception will be raised. You need to handle this exception.

2020-08-18 16:08 UTC, AlexErAmp commented on flash.py
> +    out = subprocess.run(
If `check` is `true`, and the process exits with a non-zero exit code, a `CalledProcessError` exception will be raised. You need to handle this exception.

2020-08-18 16:08 UTC, AlexErAmp commented on flash.py
> +if not check_esptool():
Place below code in `main()` function. Call the `main` function from the construct:
`if __name__ == "__main__":`

2020-08-19 13:28 UTC, AlexErAmp requested changes

2020-08-19 13:28 UTC, AlexErAmp commented on flash.py
> +            print("Error: connection lost. Reconnect your board and relaunch script.")
Duplicate code. You can do this:
```suggestion
elif error.returncode == 1 or error.returncode == 5:
     print("Error: connection lost. Reconnect your board and relaunch script.")
```

2020-08-19 13:28 UTC, AlexErAmp commented on flash.py
> +    if not check_esptool():
Add a regular exit via ctrl-c via `try: ... except KeyboardInterrupt`

2020-08-19 13:28 UTC, AlexErAmp commented on flash.py
> +"""script for easy update esp8266 firmware with esptool"""
From PEP 257 -- Docstring Conventions:
The docstring of a script (a stand-alone program) should be usable as its "usage" message, printed when the script is invoked with incorrect or missing arguments (or perhaps with a "-h" option, for "help"). Such a docstring should document the script's function and command line syntax, environment variables, and files. Usage messages can be fairly elaborate (several screens full) and should be sufficient for a new user to use the command properly, as well as a complete quick reference to all options and arguments for the sophisticated user.

Please, add informatin about usage. Also add information that the script works with python version higher than 3.7.

2020-08-19 17:00 UTC, nkrkv approved these changes
Looks good.

Minor issues below and few notes on terms:

- Linux has directories, not folders
- Linux has serial port devices, not COM ports

2020-08-19 17:00 UTC, nkrkv commented on flash.py
> +            print("Error: firmares are lost. Reload this folder from your source.")
Cannot understand the message. Do you mean something like:

> The `./firmwares` directory not found. The working directory should be a clone of https://github.com/amperka/ESP8266-uploader-script

2020-08-20 09:36 UTC, AlexErAmp approved these changes
LGTM :+1:

2020-08-20 09:41 UTC, nkrkv approved these changes
:heart:

2020-08-21 14:58 UTC, merged